services:
  prometheus:
    image: bitnami/prometheus:2.52.0
    container_name: reactive_lab_019_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  zipkin:
    image: openzipkin/zipkin:3
    container_name: reactive_lab_019_zipkin
    ports:
      - "9411:9411"
